# NeON build file (http://github.com/c4s4/neon)

extends: [golang, git]

properties:
  LIBRARIES:
  - github.com/joho/godotenv

environment:
  GOPATH: '${GOPATH}:={_BASE}'

targets:

  test:
    doc: Run an integration test
    depends: bin
    steps:
    # test without -file option
    - write: '={BUILD_DIR}/test'
      text:  "#!/bin/sh\necho $FOO\necho $SPAM"
    - chmod: '={BUILD_DIR}/test'
      mode:  0755
    - $:  ['={BUILD_DIR}/dotrun', '={BUILD_DIR}/test']
      1=: output
      1x: true
    - if: 'output != "BAR\nEGGS"'
      then:
      - throw: "Test failed:\n={output}"
    # test with -file option
    - $:  ['={BUILD_DIR}/dotrun', '-env', '.env2', '={BUILD_DIR}/test']
      1=: output
      1x: true
    - if: 'output != "FOO\nSPAM"'
      then:
      - throw: "Test failed:\n={output}"
    - print: 'Test OK'

  release:
    doc: Perform a release
    depends: [test, version, archive]
    steps:
    - super:
